#pragma once

asm(
    "shift_multiply_a:\n\t"
    "move.l 8(%sp), %d1\n\t" // d1 = x2
    "move.w #16, %a0\n\t" // a0 = 16
    "moveq  #0, %d0\n\t" // d0 = 0
    "smulL3:\n\t"
    "add.l  %d1, %d1\n\t" // d1 = x2 * 2
    "add.l  %d0, %d0\n\t" // d0 = 0 * 2
    "btst   #16, %d1\n\t" // d1の16ビット目をチェック
    "jeq    smulL2\n\t" // 16ビット目が0ならば
    "add.l  4(%sp), %d0\n\t" // d0 = d0 + x1
    "smulL2:\n\t"
    "subq.l #1, %a0\n\t" // a0を1減らす
    "cmp.w  #0, %a0\n\t" // a0が0かどうかをチェック
    "jne    smulL3\n\t" // a0が0でなければループを続ける
    "rts\n\t"
);
asm(
    "shift_divide_a:\n\t"
    "move.l 4(%sp), %a1\n\t" // a1 = x1
    "move.l 8(%sp), %d1\n\t" // d1 = x2
    "swap   %d1\n\t" // d1の上位と下位を入れ替える
    "clr.w  %d1\n\t" // d1の下位16ビットをクリア
    "move.w #16, %a0\n\t" // a0 = 16
    "moveq  #0, %d0\n\t" // d0 = 0
    "sdivL10:\n\t"
    "asr.l  #1, %d1\n\t" // d1を右シフト（2で割る）
    "add.l  %d0, %d0\n\t" // d0を2倍にする
    "cmp.l  %d1, %a1\n\t" // d1とx1を比較
    "jlt    sdivL9\n\t" // d1 < x1ならば
    "addq.l #1, %d0\n\t" // d0を1増やす
    "sub.l  %d1, % a1\n\t" // a1 = x1 - d1
    "sdivL9:\n\t"
    "subq.l #1, %a0\n\t" // a0を1減らす
    "cmp.w  #0, %a0\n\t" // a0が0かどうかをチェック
    "jne    sdivL10\n\t" // a0が0でなければループを続ける
    "rts\n\t"
);
asm(
    "sys_multiply_a:\n\t"
    "move.l %d1, -(%sp)\n\t"  // スタックに d1 を保存
    "move.l 8(%sp), %d0\n\t"  // d0 = x1
    "move.l 12(%sp), %d1\n\t" // d1 = x2
    "dc.w   0xfe00\n\t"       // __LMUL
    "move.l (%sp)+, %d1\n\t"  // スタックから d1 を戻す
    "rts\n\t"
);
asm(
    "sys_divide_a:\n\t"
    "move.l %d1, -(%sp)\n\t"  // スタックに d1 を保存
    "move.l 8(%sp), %d0\n\t"  // d0 = x1
    "move.l 12(%sp), %d1\n\t" // d1 = x2
    "dc.w   0xfe01\n\t"       // __LDIV
    "move.l (%sp)+, %d1\n\t"  // スタックから d1 を戻す
    "rts\n\t"
);
asm(
    "pset_only_a:\n\t"
    "movem.l  %d0-%d2/%a0, -(%sp)\n\t"
    "move.l   20(%sp), %d1\n\t"
    "move.l   24(%sp), %d2\n\t"
    "movea.l  %d1, %a0\n\t"
    "adda.l   %d1, %a0\n\t"  // a0 = x1 * 2
    "moveq.l  #10, %d0\n\t"
    "add.l    g_gsize, %d0\n\t"
    "lsl.l    %d0, %d2\n\t"  // d2 = y1 * (1024 << g_gsize)
    "adda.l   %d2, %a0\n\t"  // a0 = x1 * 2 + y1 * (1024 << g_gsize)
    "adda.l   g_gaddr, %a0\n\t" // a0 = g_gaddr + x1 * 2 + y1 * (1024 << g_gsize)
    "move.w   28(%sp), %d0\n\t"
    "move.w   %d0, (%a0)\n\t"
    "movem.l  (%sp)+, %d0-%d2/%a0\n\t"
    "rts\n\t"
);
asm(
    "drawlinex_a:\n\t"
    "movem.l #7966,-(%sp)\n\t"
    "move.l 44(%sp),%a4\n\t"
    "move.l 48(%sp),%a3\n\t"
    "move.l 52(%sp),%d7\n\t"
    "move.l 56(%sp),%d6\n\t"
    "move.l 60(%sp),%d5\n\t"
    "move.l %d7,%d3\n\t"
    "sub.l %a4,%d3\n\t"
    "move.l %d6,%d4\n\t"
    "sub.l %a3,%d4\n\t"
    "move.l %d4,%d1\n\t"
    "jpl dlxxL100\n\t"
    "neg.l %d1\n\t"
    "dlxxL100:\n\t"
    "move.l %d3,%d0\n\t"
    "jpl dlxxL101\n\t"
    "neg.l %d0\n\t"
    "dlxxL101:\n\t"
    "cmp.l %d1,%d0\n\t"
    "jle dlxxL99\n\t"
    "moveq #0,%d6\n\t"
    "lea __divsi3,%a5\n\t"
    "lea pset_only_a,%a6\n\t"
    "tst.l %d3\n\t"
    "jlt dlxxL102\n\t"
    "dlxxL103:\n\t"
    "cmp.l %a4,%d7\n\t"
    "jgt dlxxL104\n\t"
    "dlxxL98:\n\t"
    "movem.l (%sp)+,#30968\n\t"
    "rts\n\t"
    "dlxxL104:\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "jsr (%a5)\n\t"
    "addq.l #8,%sp\n\t"
    "pea (%a3,%d0.l)\n\t"
    "move.l %a4,-(%sp)\n\t"
    "jsr (%a6)\n\t"
    "addq.l #1,%a4\n\t"
    "add.l %d4,%d6\n\t"
    "lea (12,%sp),%sp\n\t"
    "jra dlxxL103\n\t"
    "dlxxL105:\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "jsr (%a5)\n\t"
    "addq.l #8,%sp\n\t"
    "pea (%a3,%d0.l)\n\t"
    "move.l %a4,-(%sp)\n\t"
    "jsr (%a6)\n\t"
    "subq.l #1,%a4\n\t"
    "sub.l %d4,%d6\n\t"
    "lea (12,%sp),%sp\n\t"
    "dlxxL102:\n\t"
    "cmp.l %a4,%d7\n\t"
    "jlt dlxxL105\n\t"
    "jra dlxxL98\n\t"
    "dlxxL99:\n\t"
    "moveq #0,%d7\n\t"
    "lea __divsi3,%a5\n\t"
    "lea pset_only_a,%a6\n\t"
    "tst.l %d4\n\t"
    "jlt dlxxL107\n\t"
    "dlxxL108:\n\t"
    "cmp.l %a3,%d6\n\t"
    "jle dlxxL98\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "jsr (%a5)\n\t"
    "addq.l #8,%sp\n\t"
    "pea (%a4,%d0.l)\n\t"
    "jsr (%a6)\n\t"
    "addq.l #1,%a3\n\t"
    "add.l %d3,%d7\n\t"
    "lea (12,%sp),%sp\n\t"
    "jra dlxxL108\n\t"
    "dlxxL110:\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "jsr (%a5)\n\t"
    "addq.l #8,%sp\n\t"
    "pea (%a4,%d0.l)\n\t"
    "jsr (%a6)\n\t"
    "subq.l #1,%a3\n\t"
    "sub.l %d3,%d7\n\t"
    "lea (12,%sp),%sp\n\t"
    "dlxxL107:\n\t"
    "cmp.l %a3,%d6\n\t"
    "jlt dlxxL110\n\t"
    "jra dlxxL98\n\t"
);
// DirectDrawLineInit
asm(
    "drawlineinitx_a:\n\t"
    "moveq #-1,%d0\n\t"
    "move.l %d0,direct_draw_x\n\t"
    "rts\n\t"
);
// DirectDrawLineTo
asm(
    "drawlinetox_a:\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l 16(%sp),%d4\n\t"
    "move.l 20(%sp),%d3\n\t"
    "move.l direct_draw_x,%d0\n\t"
    "jmi dltxL113\n\t"
    "move.l 24(%sp),-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l direct_draw_y,-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l 32(%sp),-(%sp)\n\t"
    "jsr drawlinex_a\n\t"
    "lea (24,%sp),%sp\n\t"
    "dltxL113:\n\t"
    "move.l %d4,direct_draw_x\n\t"
    "move.l %d3,direct_draw_y\n\t"
    "move.l (%sp)+,%d3\n\t"
    "move.l (%sp)+,%d4\n\t"
    "rts\n\t"
);
// deg_to_rad
asm(
    "deg_to_radx_a:\n\t"
    "move.l 4(%sp),-(%sp)\n\t"
    "jsr __floatsidf\n\t"
    "move.l #-266631570,(%sp)\n\t"
    "move.l #1074340345,-(%sp)\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr __muldf3\n\t"
    "lea (12,%sp),%sp\n\t"
    "clr.l (%sp)\n\t"
    "move.l #1080459264,-(%sp)\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr __divdf3\n\t"
    "lea (16,%sp),%sp\n\t"
    "rts\n\t"
);
// DirectDrawArcTo
//asm(
//    "drawarctox_a:\n\t"
//    "lea (-36,%sp),%sp\n\t"
//    "movem.l #7966,-(%sp)\n\t"
//    "move.l 76(%sp),%d7\n\t"
//    "move.l 88(%sp),%d6\n\t"
//    "move.l 92(%sp),%d5\n\t"
//    "move.l 104(%sp),%a5\n\t"
//    "move.l %d6,%d3\n\t"
//    "jpl datxL128\n\t"
//    "addq.l #1,%d3\n\t"
//    "datxL128:\n\t"
//    "asr.l #1,%d3\n\t"
//    "add.l 80(%sp),%d3\n\t"
//    "move.l %d5,%d0\n\t"
//    "jpl datxL129\n\t"
//    "addq.l #1,%d0\n\t"
//    "datxL129:\n\t"
//    "asr.l #1,%d0\n\t"
//    "add.l 84(%sp),%d0\n\t"
//    "move.l %d0,44(%sp)\n\t"
//    "move.l 96(%sp),%d4\n\t"
//    "move.l %d4,%a6\n\t"
//    "add.l 100(%sp),%a6\n\t"
//    "lea __floatsidf,%a4\n\t"
//    "lea __muldf3,%a3\n\t"
//    "datxL126:\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "move.l %d0,%a0\n\t"
//    "move.l %d1,%a1\n\t"
//    "move.l %a0,52(%sp)\n\t"
//    "move.l %a1,56(%sp)\n\t"
//    "move.l %d5,(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "addq.l #4,%sp\n\t"
//    "move.l %d0,%a0\n\t"
//    "move.l %d1,%a1\n\t"
//    "move.l %a0,56(%sp)\n\t"
//    "move.l %a1,60(%sp)\n\t"
//    "cmp.l %a6,%d4\n\t"
//    "jlt datxL127\n\t"
//    "move.l %a6,-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "lea __muldf3,%a3\n\t"
//    "move.l #-266631570,(%sp)\n\t"
//    "move.l #1074340345,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "clr.l (%sp)\n\t"
//    "move.l #1080459264,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr __divdf3\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l %d0,%a0\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %a0,-(%sp)\n\t"
//    "move.l %a0,44(%sp)\n\t"
//    "move.l %d1,48(%sp)\n\t"
//    "jsr cos\n\t"
//    "addq.l #8,%sp\n\t"
//    "move.l %d0,%d4\n\t"
//    "move.l %d1,%d5\n\t"
//    "move.l 36(%sp),%a0\n\t"
//    "move.l 40(%sp),%a1\n\t"
//    "move.l %a1,-(%sp)\n\t"
//    "move.l %a0,-(%sp)\n\t"
//    "jsr sin\n\t"
//    "addq.l #8,%sp\n\t"
//    "move.l %a5,88(%sp)\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "clr.l (%sp)\n\t"
//    "move.l #1071644672,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "lea __fixdfsi,%a4\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "addq.l #8,%sp\n\t"
//    "move.l 44(%sp),%d1\n\t"
//    "sub.l %d0,%d1\n\t"
//    "move.l %d1,84(%sp)\n\t"
//    "move.l 52(%sp),-(%sp)\n\t"
//    "move.l 52(%sp),-(%sp)\n\t"
//    "move.l %d5,-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "clr.l (%sp)\n\t"
//    "move.l #1071644672,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "addq.l #8,%sp\n\t"
//    "add.l %d3,%d0\n\t"
//    "move.l %d0,80(%sp)\n\t"
//    "move.l %d7,76(%sp)\n\t"
//    "movem.l (%sp)+,#30968\n\t"
//    "lea (36,%sp),%sp\n\t"
//    "jra drawlinetox_a\n\t"
//    "datxL127:\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "move.l #-266631570,(%sp)\n\t"
//    "move.l #1074340345,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "clr.l (%sp)\n\t"
//    "move.l #1080459264,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr __divdf3\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l %d0,%a0\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %a0,-(%sp)\n\t"
//    "move.l %a0,44(%sp)\n\t"
//    "move.l %d1,48(%sp)\n\t"
//    "jsr cos\n\t"
//    "addq.l #8,%sp\n\t"
//    "move.l %d0,%d2\n\t"
//    "move.l %d2,%d0\n\t"
//    "move.l %d0,64(%sp)\n\t"
//    "move.l %d1,68(%sp)\n\t"
//    "move.l 36(%sp),%a0\n\t"
//    "move.l 40(%sp),%a1\n\t"
//    "move.l %a1,-(%sp)\n\t"
//    "move.l %a0,-(%sp)\n\t"
//    "jsr sin\n\t"
//    "addq.l #4,%sp\n\t"
//    "move.l %a5,(%sp)\n\t"
//    "move.l 64(%sp),-(%sp)\n\t"
//    "move.l 64(%sp),-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "clr.l (%sp)\n\t"
//    "move.l #1071644672,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "lea __fixdfsi,%a0\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "move.l %a0,48(%sp)\n\t"
//    "jsr (%a0)\n\t"
//    "addq.l #8,%sp\n\t"
//    "move.l 48(%sp),%d1\n\t"
//    "sub.l %d0,%d1\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l 84(%sp),-(%sp)\n\t"
//    "move.l 84(%sp),-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "clr.l (%sp)\n\t"
//    "move.l #1071644672,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "move.l 52(%sp),%a0\n\t"
//    "jsr (%a0)\n\t"
//    "addq.l #8,%sp\n\t"
//    "move.l %d0,%a0\n\t"
//    "pea (%a0,%d3.l)\n\t"
//    "move.l %d7,-(%sp)\n\t"
//    "jsr drawlinetox_a\n\t"
//    "addq.l #5,%d4\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "jra datxL126\n\t"
//);
asm(
    "drawarctox_a:\n\t"
    //    "lea (-20,%sp),%sp\n\t"
    //    "movem.l #7966,-(%sp)\n\t"
    //    "move.l 60(%sp),52(%sp)\n\t"
    //    "move.l 72(%sp),%d7\n\t"
    //    "move.l 76(%sp),%d6\n\t"
    //    "move.l 88(%sp),%a4\n\t"
    //    "move.l %d7,%d0\n\t"
    //    "jpl datxL418\n\t"
    //    "addq.l #1,%d0\n\t"
    //    "datxL418:\n\t"
    //    "asr.l #1,%d0\n\t"
    //    "add.l 64(%sp),%d0\n\t"
    //    "move.l %d0,40(%sp)\n\t"
    //    "move.l %d6,%d0\n\t"
    //    "jpl datxL419\n\t"
    //    "addq.l #1,%d0\n\t"
    //    "datxL419:\n\t"
    //    "asr.l #1,%d0\n\t"
    //    "add.l 68(%sp),%d0\n\t"
    //    "move.l %d0,44(%sp)\n\t"
    //    "move.l 80(%sp),%d3\n\t"
    //    "move.l %d3,%d5\n\t"
    //    "add.l 84(%sp),%d5\n\t"
    //    "lea __floatsisf,%a6\n\t"
    //    "lea tab_cos_a,%a5\n\t"
    //    "lea __mulsf3,%a3\n\t"
    //    "datxL416:\n\t"
    //    "move.l %d7,-(%sp)\n\t"
    //    "jsr (%a6)\n\t"
    //    "move.l %d0,%d4\n\t"
    //    "move.l %d6,(%sp)\n\t"
    //    "jsr (%a6)\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l %d0,48(%sp)\n\t"
    //    "cmp.l %d5,%d3\n\t"
    //    "jlt datxL417\n\t"
    //    "move.l %d5,-(%sp)\n\t"
    //    "jsr (%a5)\n\t"
    //    "lea __mulsf3,%a3\n\t"
    //    "move.l %d4,(%sp)\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a3)\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l #0x3f000000,(%sp)\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a3)\n\t"
    //    "addq.l #8,%sp\n\t"
    //    "lea __fixsfsi,%a5\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a5)\n\t"
    //    "move.l 44(%sp),%d3\n\t"
    //    "add.l %d0,%d3\n\t"
    //    "move.l %d5,(%sp)\n\t"
    //    "jsr _Z7tab_sini\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l %a4,72(%sp)\n\t"
    //    "move.l 48(%sp),-(%sp)\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a3)\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l #0x3f000000,(%sp)\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a3)\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l %d0,(%sp)\n\t"
    //    "jsr (%a5)\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l 44(%sp),%d1\n\t"
    //    "sub.l %d0,%d1\n\t"
    //    "move.l %d1,68(%sp)\n\t"
    //    "move.l %d3,64(%sp)\n\t"
    //    "move.l 52(%sp),60(%sp)\n\t"
    //    "movem.l (%sp)+,#30968\n\t"
    //    "lea (20,%sp),%sp\n\t"
    //    "jra drawlinetox_a\n\t"
    //    "datxL417:\n\t"
    //    "move.l %d3,-(%sp)\n\t"
    //    "jsr (%a5)\n\t"
    //    "move.l %d4,(%sp)\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a3)\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l #0x3f000000,(%sp)\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a3)\n\t"
    //    "addq.l #8,%sp\n\t"
    //    "lea __fixsfsi,%a0\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "move.l %a0,40(%sp)\n\t"
    //    "jsr (%a0)\n\t"
    //    "move.l 44(%sp),%d4\n\t"
    //    "add.l %d0,%d4\n\t"
    //    "move.l %d3,(%sp)\n\t"
    //    "jsr tab_sin_a\n\t"
    //    "move.l %a4,(%sp)\n\t"
    //    "move.l 52(%sp),-(%sp)\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a3)\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l #0x3f000000,(%sp)\n\t"
    //    "move.l %d0,-(%sp)\n\t"
    //    "jsr (%a3)\n\t"
    //    "addq.l #4,%sp\n\t"
    //    "move.l %d0,(%sp)\n\t"
    //    "move.l 44(%sp),%a0\n\t"
    //    "jsr (%a0)\n\t"
    //    "move.l 52(%sp),%d1\n\t"
    //    "sub.l %d0,%d1\n\t"
    //    "move.l %d1,(%sp)\n\t"
    //    "move.l %d4,-(%sp)\n\t"
    //    "move.l 64(%sp),-(%sp)\n\t"
    //    "jsr drawlinetox_a\n\t"
    //    "addq.l #5,%d3\n\t"
    //    "lea (16,%sp),%sp\n\t"
    //    "jra datxL416\n\t"
);
// DirectDrawArc
asm(
    "drawarcx_a:\n\t"
    "moveq #-1,%d0\n\t"
    "move.l %d0,direct_draw_x\n\t"
    "jra drawarctox_a\n\t"
);
// DirectDrawPie
asm(
    "drawpiex_a:\n\t"
    "subq.l #4,%sp\n\t"
    "movem.l #7966,-(%sp)\n\t"
    "move.l 44(%sp),%d5\n\t"
    "move.l 48(%sp),%a6\n\t"
    "move.l 52(%sp),%d7\n\t"
    "move.l 56(%sp),%a4\n\t"
    "move.l 60(%sp),%a5\n\t"
    "move.l 64(%sp),36(%sp)\n\t"
    "move.l 68(%sp),%a3\n\t"
    "move.l 72(%sp),%d6\n\t"
    "moveq #-1,%d0\n\t"
    "move.l %d0,direct_draw_x\n\t"
    "move.l %a5,%d4\n\t"
    "jpl dpixL146\n\t"
    "addq.l #1,%d4\n\t"
    "dpixL146:\n\t"
    "asr.l #1,%d4\n\t"
    "add.l %d7,%d4\n\t"
    "move.l %a4,%d3\n\t"
    "jpl dpixL147\n\t"
    "addq.l #1,%d3\n\t"
    "dpixL147:\n\t"
    "asr.l #1,%d3\n\t"
    "add.l %a6,%d3\n\t"
    "move.l %d6,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "jsr drawlinetox_a\n\t"
    "move.l %d6,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l 60(%sp),-(%sp)\n\t"
    "move.l %a5,-(%sp)\n\t"
    "move.l %a4,-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l %a6,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "jsr drawarctox_a\n\t"
    "lea (48,%sp),%sp\n\t"
    "move.l %d6,56(%sp)\n\t"
    "move.l %d4,52(%sp)\n\t"
    "move.l %d3,48(%sp)\n\t"
    "move.l %d5,44(%sp)\n\t"
    "movem.l (%sp)+,#30968\n\t"
    "addq.l #4,%sp\n\t"
    "jra drawlinetox_a\n\t"
);
// DirectDrawRoundedRectangle
asm(
    "drawroundedrectanglex_a:\n\t"
    "lea (-24,%sp),%sp\n\t"
    "movem.l #7966,-(%sp)\n\t"
    "move.l 64(%sp),%d3\n\t"
    "move.l 68(%sp),%a3\n\t"
    "move.l 72(%sp),%d5\n\t"
    "move.l 80(%sp),44(%sp)\n\t"
    "move.l 84(%sp),%a5\n\t"
    "move.l 88(%sp),%d6\n\t"
    "move.l 92(%sp),%d4\n\t"
    "moveq #-1,%d0\n\t"
    "move.l %d0,direct_draw_x\n\t"
    "move.l %d6,%d0\n\t"
    "add.l %d6,%d0\n\t"
    "move.l %d0,40(%sp)\n\t"
    "move.l %a5,%d7\n\t"
    "add.l %a5,%d7\n\t"
    "move.l %a3,%d0\n\t"
    "add.l 76(%sp),%d0\n\t"
    "move.l %d0,52(%sp)\n\t"
    "move.l %d0,%a0\n\t"
    "sub.l %d7,%a0\n\t"
    "move.l %a0,48(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "pea 90.w\n\t"
    "clr.l -(%sp)\n\t"
    "move.l 52(%sp),-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %a0,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "lea drawarctox_a,%a4\n\t"
    "jsr (%a4)\n\t"
    "lea (28,%sp),%sp\n\t"
    "move.l %d4,(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "pea (%a5,%a3.l)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "lea drawlinetox_a,%a6\n\t"
    "jsr (%a6)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "pea 90.w\n\t"
    "pea 90.w\n\t"
    "move.l 68(%sp),-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "jsr (%a4)\n\t"
    "move.l %d5,%d0\n\t"
    "add.l 92(%sp),%d0\n\t"
    "move.l %d0,92(%sp)\n\t"
    "sub.l %d6,%d0\n\t"
    "move.l %d0,104(%sp)\n\t"
    "lea (44,%sp),%sp\n\t"
    "move.l %d4,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "jsr (%a6)\n\t"
    "move.l 72(%sp),%d0\n\t"
    "sub.l %d6,%d0\n\t"
    "move.l %d4,-(%sp)\n\t"
    "pea 90.w\n\t"
    "pea 180.w\n\t"
    "move.l 68(%sp),-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d0,84(%sp)\n\t"
    "jsr (%a4)\n\t"
    "lea (44,%sp),%sp\n\t"
    "move.l %d4,(%sp)\n\t"
    "move.l 48(%sp),-(%sp)\n\t"
    "move.l 56(%sp),%a0\n\t"
    "pea (%a0,%a5.l)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "jsr (%a6)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "pea 90.w\n\t"
    "pea 270.w\n\t"
    "move.l 68(%sp),-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l 72(%sp),%d0\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l 88(%sp),-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "jsr (%a4)\n\t"
    "lea (48,%sp),%sp\n\t"
    "move.l %d4,76(%sp)\n\t"
    "add.l %d5,%d6\n\t"
    "move.l %d6,72(%sp)\n\t"
    "move.l 52(%sp),68(%sp)\n\t"
    "move.l %d3,64(%sp)\n\t"
    "movem.l (%sp)+,#30968\n\t"
    "lea (24,%sp),%sp\n\t"
    "jra drawlinetox_a\n\t"
);
// DrawHLine
//asm(
//  "drawhlinex_a:\n\t"
//	"movem.l #6160,-(%sp)\n\t"  // 6160 = 00011000 00010000
//	"move.l 20(%sp),%d3\n\t"    // d3 = x = x1
//	"move.l %d3,%d4\n\t"        // d4 = x1
//	"add.l 28(%sp),%d4\n\t"     // d4 = x1 + w
//	"lea _Z5psetxiii,%a3\n\t"   // a3 = psetxiii
//  "dhlL162:\n\t"
//	"cmp.l %d4,%d3\n\t"         // Compare x1 + w with x
//	"jle dhlL163\n\t"           // If x <= x1 + w, jump to dhlL163
//	"movem.l (%sp)+,#2072\n\t"  // 2072 = 00001000 00011000
//    "rts\n\t"
//  "dhlL163:\n\t"
//	"move.l 32(%sp),-(%sp)\n\t" // color
//	"move.l 28(%sp),-(%sp)\n\t" // y1
//	"move.l %d3,-(%sp)\n\t"     // x
//	"jsr (%a3)\n\t"             // Call psetxiii
//	"addq.l #1,%d3\n\t"         // Increment x
//	"lea (12,%sp),%sp\n\t"      // Clean up stack
//    "jra dhlL162\n\t"
//);
asm(
    "drawhlinex_a:\n\t"
    "movem.l %d1-%d3/%a3,-(%sp)\n\t"
    "move.l 24(%sp),%d3\n\t"    // d3 = x = x1
    "move.l %d3,%d4\n\t"        // d4 = x1
    "add.l 32(%sp),%d4\n\t"     // d4 = x1 + w

    "move.l   28(%sp),%d1\n\t"    // d1 = y1
    "moveq.l  #10, %d2\n\t"
    "add.l    g_gsize, %d2\n\t"
    "lsl.l    %d2, %d1\n\t"     // d1 = y1 * (1024 << g_gsize)
    "move.l   g_gaddr, %a3\n\t" // a3 = g_gaddr
    "adda.l   %d1, %a3\n\t"      // a3 = g_gaddr + y1 * (1024 << g_gsize)
    "adda.l   %d3, %a3\n\t"      // a3 = g_gaddr + y1 * (1024 << g_gsize) + x1
    "adda.l   %d3, %a3\n\t"      // a3 = g_gaddr + y1 * (1024 << g_gsize) + x1 * 2

    "dhlL162:\n\t"
    "cmp.l %d4,%d3\n\t"         // Compare x1 + w with x
    "jle dhlL163\n\t"           // If x <= x1 + w, jump to dhlL163
    "movem.l (%sp)+, %d1-%d3/%a3\n\t"
    "rts\n\t"
    "dhlL163:\n\t"
    "move.l 36(%sp),(%a3)\n\t"  // color
    "addq.l #1,%d3\n\t"         // Increment x
    "addq.l #2,%a3\n\t"         // Increment (x, y1) address
    "jra dhlL162\n\t"
);
// DirectFillEllipse
// pset_only_a を呼び出す
//asm(
//    "fillellipsex_a:\n\t"
//    "subq.l #4,%sp\n\t"
//    "movem.l #7966,-(%sp)\n\t"
//    "move.l 52(%sp),%a0\n\t"
//    "move.l 56(%sp),%d3\n\t"
//    "jpl dfexL156\n\t"
//    "addq.l #1,%d3\n\t"
//    "dfexL156:\n\t"
//    "asr.l #1,%d3\n\t"
//    "add.l 48(%sp),%d3\n\t"
//    "move.l 60(%sp),%d0\n\t"
//    "jpl dfexL157\n\t"
//    "addq.l #1,%d0\n\t"
//    "dfexL157:\n\t"
//    "asr.l #1,%d0\n\t"
//    "move.l %d0,%d7\n\t"
//    "add.l %a0,%d7\n\t"
//    "move.l %a0,%d6\n\t"
//    "move.l 60(%sp),%d0\n\t"
//    "add.l %a0,%d0\n\t"
//    "move.l %d0,36(%sp)\n\t"
//    "lea __floatsidf,%a3\n\t"
//    "lea pset_only_a,%a4\n\t"
//    "dfexL152:\n\t"
//    "cmp.l 36(%sp),%d6\n\t"
//    "jlt dfexL155\n\t"
//    "movem.l (%sp)+,#30968\n\t"
//    "addq.l #4,%sp\n\t"
//    "rts\n\t"
//    "dfexL155:\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "move.l %d0,%d4\n\t"
//    "move.l %d1,%d5\n\t"
//    "move.l %d7,(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea __subdf3,%a5\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "move.l %d5,-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "jsr (%a5)\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l %d0,%d4\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "jsr __adddf3\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l %d0,%d4\n\t"
//    "move.l %d1,%d5\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "move.l %d5,-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "jsr __divdf3\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l %d0,%d4\n\t"
//    "lea __muldf3,%a6\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "jsr (%a6)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "clr.l -(%sp)\n\t"
//    "move.l #1072693248,-(%sp)\n\t"
//    "jsr (%a5)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr sqrt\n\t"
//    "move.l %d0,%d4\n\t"
//    "move.l %d1,%d5\n\t"
//    "move.l 64(%sp),-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "move.l %d5,(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a6)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "clr.l (%sp)\n\t"
//    "move.l #1071644672,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a6)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr __fixdfsi\n\t"
//    "move.l %d3,%d5\n\t"
//    "sub.l %d0,%d5\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l %d3,%d4\n\t"
//    "add.l %d0,%d4\n\t"
//    "dfexL153:\n\t"
//    "cmp.l %d4,%d5\n\t"
//    "jle dfexL154\n\t"
//    "addq.l #1,%d6\n\t"
//    "jra dfexL152\n\t"
//    "dfexL154:\n\t"
//    "move.l 64(%sp),-(%sp)\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "move.l %d5,-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "addq.l #1,%d5\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "jra dfexL153\n\t"
//);
// drawhlinex_a を呼び出す・平方根を計算する(動作するが遅い)
asm(
    "fillellipsex_a:\n\t"
    "subq.l #4,%sp\n\t"
    "movem.l #7966,-(%sp)\n\t"
    "move.l 52(%sp),%a0\n\t"
    "move.l 56(%sp),%d0\n\t"
    "jpl felxL174\n\t"
    "addq.l #1,%d0\n\t"
    "felxL174:\n\t"
    "asr.l #1,%d0\n\t"
    "add.l 48(%sp),%d0\n\t"
    "move.l %d0,36(%sp)\n\t"
    "move.l 60(%sp),%d0\n\t"
    "jpl felxL175\n\t"
    "addq.l #1,%d0\n\t"
    "felxL175:\n\t"
    "asr.l #1,%d0\n\t"
    "move.l %d0,%d6\n\t"
    "add.l %a0,%d6\n\t"
    "move.l %a0,%d3\n\t"
    "move.l 60(%sp),%d7\n\t"
    "add.l %a0,%d7\n\t"
    "lea __floatsidf,%a3\n\t"
    "lea __subdf3,%a4\n\t"
    "lea __adddf3,%a5\n\t"
    "felxL172:\n\t"
    "cmp.l %d7,%d3\n\t"
    "jlt felxL173\n\t"
    "movem.l (%sp)+,#30968\n\t"
    "addq.l #4,%sp\n\t"
    "rts\n\t"
    "felxL173:\n\t"
    "move.l %d3,-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "move.l %d0,%d4\n\t"
    "move.l %d1,%d5\n\t"
    "move.l %d6,(%sp)\n\t"
    "jsr (%a3)\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "jsr (%a4)\n\t"
    "lea (16,%sp),%sp\n\t"
    "move.l %d0,%d4\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "jsr (%a5)\n\t"
    "lea (16,%sp),%sp\n\t"
    "move.l %d0,%d4\n\t"
    "move.l %d1,%d5\n\t"
    "move.l 60(%sp),-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "jsr __divdf3\n\t"
    "lea (16,%sp),%sp\n\t"
    "move.l %d0,%d4\n\t"
    "lea __muldf3,%a6\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "jsr (%a6)\n\t"
    "lea (12,%sp),%sp\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "clr.l -(%sp)\n\t"
    "move.l #1072693248,-(%sp)\n\t"
    "jsr (%a4)\n\t"
    "lea (12,%sp),%sp\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr sqrt\n\t"
    "move.l %d0,%d4\n\t"
    "move.l %d1,%d5\n\t"
    "move.l 64(%sp),-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "move.l %d5,(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr (%a6)\n\t"
    "lea (12,%sp),%sp\n\t"
    "clr.l (%sp)\n\t"
    "move.l #1071644672,-(%sp)\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr (%a6)\n\t"
    "lea (12,%sp),%sp\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr __fixdfsi\n\t"
    "addq.l #8,%sp\n\t"
    "move.l 72(%sp),-(%sp)\n\t"
    "move.l %d0,%d1\n\t"
    "add.l %d0,%d1\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l 56(%sp),%d1\n\t"
    "sub.l %d0,%d1\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l 68(%sp),-(%sp)\n\t"
    "jsr drawhlinex_a\n\t"
    "addq.l #1,%d3\n\t"
    "lea (28,%sp),%sp\n\t"
    "jra felxL172\n\t"
);
// drawhlinex_a を呼び出す・楕円の座標を表から取得する
//asm(
//    "fillellipsex_a:\n\t"
//    "movem.l #7964,-(%sp)\n\t"
//    "move.l 44(%sp),%d3\n\t"
//    "move.l 52(%sp),%d4\n\t"
//    "move.l 48(%sp),%d5\n\t"
//    "jpl felxL435\n\t"
//    "addq.l #1,%d5\n\t"
//    "felxL435:\n\t"
//    "asr.l #1,%d5\n\t"
//    "move.l %d5,%d6\n\t"
//    "add.l 40(%sp),%d6\n\t"
//    "move.l %d4,%d0\n\t"
//    "jpl felxL436\n\t"
//    "addq.l #1,%d0\n\t"
//    "felxL436:\n\t"
//    "asr.l #1,%d0\n\t"
//    "move.l %d0,%a5\n\t"
//    "move.l %d0,%d7\n\t"
//    "add.l %d3,%d7\n\t"
//    "add.l %d3,%d4\n\t"
//    "lea tab_opposite_edgex_a,%a3\n\t"
//    "lea drawhlinex_a,%a4\n\t"
//    "felxL433:\n\t"
//    "cmp.l %d4,%d3\n\t"
//    "jlt felxL434\n\t"
//    "movem.l (%sp)+,#14584\n\t"
//    "rts\n\t"
//    "felxL434:\n\t"
//    "move.l %d5,-(%sp)\n\t"
//    "move.l %a5,-(%sp)\n\t"
//    "move.l %d3,%d0\n\t"
//    "sub.l %d7,%d0\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l 56(%sp),-(%sp)\n\t"
//    "move.l %d0,%d1\n\t"
//    "add.l %d0,%d1\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d3,-(%sp)\n\t"
//    "move.l %d6,%d1\n\t"
//    "sub.l %d0,%d1\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l 52(%sp),-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "addq.l #1,%d3\n\t"
//    "lea (20,%sp),%sp\n\t"
//    "jra felxL433\n\t"
//);
// DirectFillRoundedRectangle
// pset_only_a を呼び出す(動作するが遅い)
//asm(
//    "fillroundedrectanglex_a:\n\t"
//    "lea (-16,%sp),%sp\n\t"
//    "movem.l #7966,-(%sp)\n\t"
//    "move.l 60(%sp),%d5\n\t"
//    "move.l 64(%sp),%d3\n\t"
//    "move.l 76(%sp),%d0\n\t"
//    "add.l %d5,%d0\n\t"
//    "move.l %d0,44(%sp)\n\t"
//    "move.l 80(%sp),%d4\n\t"
//    "add.l %d3,%d4\n\t"
//    "move.l %d3,%d0\n\t"
//    "add.l 72(%sp),%d0\n\t"
//    "move.l %d0,40(%sp)\n\t"
//    "move.l %d0,%a5\n\t"
//    "subq.l #1,%a5\n\t"
//    "move.l 68(%sp),%d0\n\t"
//    "add.l %d5,%d0\n\t"
//    "sub.l 76(%sp),%d0\n\t"
//    "move.l %d0,48(%sp)\n\t"
//    "lea pset_only_a,%a4\n\t"
//    "frrxL160:\n\t"
//    "cmp.l %d3,%d4\n\t"
//    "jgt frrxL163\n\t"
//    "move.l 40(%sp),%a6\n\t"
//    "sub.l 80(%sp),%a6\n\t"
//    "move.l 68(%sp),%d3\n\t"
//    "add.l %d5,%d3\n\t"
//    "lea pset_only_a,%a3\n\t"
//    "frrxL164:\n\t"
//    "cmp.l %a6,%d4\n\t"
//    "jlt frrxL167\n\t"
//    "movem.l (%sp)+,#30968\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "rts\n\t"
//    "frrxL163:\n\t"
//    "lea __floatsidf,%a3\n\t"
//    "move.l %d3,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "move.l %d0,%d6\n\t"
//    "move.l %d1,%d7\n\t"
//    "move.l %d4,(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "lea __subdf3,%a2\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "move.l %d7,-(%sp)\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "move.l %a2,52(%sp)\n\t"
//    "jsr (%a2)\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l %d0,%d6\n\t"
//    "move.l %d1,%d7\n\t"
//    "move.l 80(%sp),-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "move.l %d7,-(%sp)\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "jsr __divdf3\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l %d0,%a0\n\t"
//    "lea __muldf3,%a6\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %a0,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %a0,-(%sp)\n\t"
//    "jsr (%a6)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "clr.l -(%sp)\n\t"
//    "move.l #1072693248,-(%sp)\n\t"
//    "move.l 52(%sp),%a2\n\t"
//    "jsr (%a2)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr sqrt\n\t"
//    "move.l %d0,%d6\n\t"
//    "move.l %d1,%d7\n\t"
//    "move.l 84(%sp),-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "move.l %d7,(%sp)\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "move.l %d1,-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a6)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d1,(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr __fixdfsi\n\t"
//    "move.l 60(%sp),%d7\n\t"
//    "sub.l %d0,%d7\n\t"
//    "lea (16,%sp),%sp\n\t"
//    "move.l 48(%sp),%d6\n\t"
//    "add.l %d0,%d6\n\t"
//    "frrxL161:\n\t"
//    "cmp.l %d6,%d7\n\t"
//    "jle frrxL162\n\t"
//    "addq.l #1,%d3\n\t"
//    "subq.l #1,%a5\n\t"
//    "jra frrxL160\n\t"
//    "frrxL162:\n\t"
//    "move.l 84(%sp),-(%sp)\n\t"
//    "move.l %d3,-(%sp)\n\t"
//    "move.l %d7,-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "move.l 96(%sp),-(%sp)\n\t"
//    "move.l %a5,-(%sp)\n\t"
//    "move.l %d7,-(%sp)\n\t"
//    "jsr (%a4)\n\t"
//    "addq.l #1,%d7\n\t"
//    "lea (24,%sp),%sp\n\t"
//    "jra frrxL161\n\t"
//    "frrxL165:\n\t"
//    "move.l 84(%sp),-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "addq.l #1,%d6\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "frrxL166:\n\t"
//    "cmp.l %d3,%d6\n\t"
//    "jlt frrxL165\n\t"
//    "addq.l #1,%d4\n\t"
//    "jra frrxL164\n\t"
//    "frrxL167:\n\t"
//    "move.l %d5,%d6\n\t"
//    "jra frrxL166\n\t"
//);
// drawhlinex_a を呼び出す・平方根を計算する
asm(
    "fillroundedrectanglex_a:\n\t"
    "lea (-12,%sp),%sp\n\t"
    "movem.l #7966,-(%sp)\n\t"
    "move.l 60(%sp),%d3\n\t"
    "move.l 56(%sp),%d0\n\t"
    "add.l 72(%sp),%d0\n\t"
    "move.l %d0,40(%sp)\n\t"
    "move.l 76(%sp),%d4\n\t"
    "add.l %d3,%d4\n\t"
    "move.l %d3,%d0\n\t"
    "add.l 68(%sp),%d0\n\t"
    "move.l %d0,44(%sp)\n\t"
    "move.l %d0,%d5\n\t"
    "lea __floatsidf,%a3\n\t"
    "lea __subdf3,%a5\n\t"
    "lea __divdf3,%a6\n\t"
    "lea __muldf3,%a4\n\t"
    "frrxL186:\n\t"
    "subq.l #1,%d5\n\t"
    "cmp.l %d3,%d4\n\t"
    "jgt frrxL187\n\t"
    "move.l 44(%sp),%d3\n\t"
    "sub.l 76(%sp),%d3\n\t"
    "lea drawhlinex_a,%a3\n\t"
    "frrxL188:\n\t"
    "cmp.l %d3,%d4\n\t"
    "jlt frrxL189\n\t"
    "movem.l (%sp)+,#30968\n\t"
    "lea (12,%sp),%sp\n\t"
    "rts\n\t"
    "frrxL187:\n\t"
    "move.l %d3,-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "move.l %d0,%d6\n\t"
    "move.l %d1,%d7\n\t"
    "move.l %d4,(%sp)\n\t"
    "jsr (%a3)\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "jsr (%a5)\n\t"
    "lea (16,%sp),%sp\n\t"
    "move.l %d0,%d6\n\t"
    "move.l %d1,%d7\n\t"
    "move.l 76(%sp),-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "jsr (%a6)\n\t"
    "lea (16,%sp),%sp\n\t"
    "move.l %d0,%a0\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %a0,-(%sp)\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %a0,-(%sp)\n\t"
    "jsr (%a4)\n\t"
    "lea (12,%sp),%sp\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "clr.l -(%sp)\n\t"
    "move.l #1072693248,-(%sp)\n\t"
    "jsr (%a5)\n\t"
    "lea (12,%sp),%sp\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr sqrt\n\t"
    "move.l %d0,%d6\n\t"
    "move.l %d1,%d7\n\t"
    "move.l 80(%sp),-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "move.l %d7,(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "move.l %d1,-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr (%a4)\n\t"
    "lea (12,%sp),%sp\n\t"
    "move.l %d1,(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr __fixdfsi\n\t"
    "addq.l #8,%sp\n\t"
    "move.l %d0,%d6\n\t"
    "add.l %d0,%d6\n\t"
    "add.l 64(%sp),%d6\n\t"
    "add.l 72(%sp),%d6\n\t"
    "sub.l 80(%sp),%d6\n\t"
    "sub.l 48(%sp),%d6\n\t"
    "move.l 48(%sp),%d7\n\t"
    "sub.l %d0,%d7\n\t"
    "move.l 88(%sp),-(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l 76(%sp),-(%sp)\n\t"
    "lea drawhlinex_a,%a0\n\t"
    "move.l %a0,64(%sp)\n\t"
    "jsr (%a0)\n\t"
    "move.l 108(%sp),-(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l 96(%sp),-(%sp)\n\t"
    "move.l 84(%sp),%a0\n\t"
    "jsr (%a0)\n\t"
    "addq.l #1,%d3\n\t"
    "lea (48,%sp),%sp\n\t"
    "jra frrxL186\n\t"
    "frrxL189:\n\t"
    "move.l 80(%sp),-(%sp)\n\t"
    "move.l 68(%sp),-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l 68(%sp),-(%sp)\n\t"
    "move.l 68(%sp),-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "addq.l #1,%d4\n\t"
    "lea (20,%sp),%sp\n\t"
    "jra frrxL188\n\t"
);
// drawhlinex_a を呼び出す・楕円の座標を表から取得する
//asm(
//    "fillroundedrectanglex_a:\n\t"
//    "movem.l #7966,-(%sp)\n\t"
//    "move.l 48(%sp),%d3\n\t"
//    "move.l 44(%sp),%a4\n\t"
//    "add.l 60(%sp),%a4\n\t"
//    "move.l 64(%sp),%d5\n\t"
//    "add.l %d3,%d5\n\t"
//    "move.l %d3,%d4\n\t"
//    "add.l 56(%sp),%d4\n\t"
//    "move.l %d4,%d7\n\t"
//    "lea tab_opposite_edgex_a,%a6\n\t"
//    "lea drawhlinex_a,%a5\n\t"
//    "frrxL438:\n\t"
//    "subq.l #1,%d7\n\t"
//    "cmp.l %d3,%d5\n\t"
//    "jgt frrxL439\n\t"
//    "sub.l 64(%sp),%d4\n\t"
//    "lea drawhlinex_a,%a3\n\t"
//    "frrxL440:\n\t"
//    "cmp.l %d4,%d5\n\t"
//    "jlt frrxL441\n\t"
//    "movem.l (%sp)+,#30968\n\t"
//    "rts\n\t"
//    "frrxL439:\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l 68(%sp),-(%sp)\n\t"
//    "move.l %d3,%d0\n\t"
//    "sub.l %d5,%d0\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a6)\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "move.l %d0,%d1\n\t"
//    "add.l %d0,%d1\n\t"
//    "add.l 44(%sp),%d1\n\t"
//    "add.l 52(%sp),%d1\n\t"
//    "sub.l 60(%sp),%d1\n\t"
//    "move.l %d1,%a3\n\t"
//    "sub.l %a4,%a3\n\t"
//    "move.l %a4,%d6\n\t"
//    "sub.l %d0,%d6\n\t"
//    "move.l 68(%sp),-(%sp)\n\t"
//    "move.l %a3,-(%sp)\n\t"
//    "move.l %d3,-(%sp)\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "move.l 56(%sp),-(%sp)\n\t"
//    "jsr (%a5)\n\t"
//    "move.l 88(%sp),-(%sp)\n\t"
//    "move.l %a3,-(%sp)\n\t"
//    "move.l %d7,-(%sp)\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "move.l 76(%sp),-(%sp)\n\t"
//    "jsr (%a5)\n\t"
//    "addq.l #1,%d3\n\t"
//    "lea (40,%sp),%sp\n\t"
//    "jra frrxL438\n\t"
//    "frrxL441:\n\t"
//    "move.l 68(%sp),-(%sp)\n\t"
//    "move.l 56(%sp),-(%sp)\n\t"
//    "move.l %d5,-(%sp)\n\t"
//    "move.l 56(%sp),-(%sp)\n\t"
//    "move.l 56(%sp),-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "addq.l #1,%d5\n\t"
//    "lea (20,%sp),%sp\n\t"
//    "jra frrxL440\n\t"
//);
asm(
    "get_coordinatex_a:\n\t"
    "movem.l #7168,-(%sp)\n\t"
    "move.l 16(%sp),%d3\n\t"
    "move.l 20(%sp),%d4\n\t"
    "move.l 28(%sp),%d5\n\t"
    "cmp.l %d4,%d5\n\t"
    "jeq gcoxL232\n\t"
    "move.l 32(%sp),%d0\n\t"
    "sub.l %d4,%d0\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l 28(%sp),%d0\n\t"
    "sub.l %d3,%d0\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr __mulsi3\n\t"
    "addq.l #8,%sp\n\t"
    "sub.l %d4,%d5\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr __divsi3\n\t"
    "addq.l #8,%sp\n\t"
    "add.l %d0,%d3\n\t"
    "gcoxL232:\n\t"
    "move.l %d3,%d0\n\t"
    "movem.l (%sp)+,#56\n\t"
    "rts\n\t"
);
//asm(
//    "filltrapezoidx_a:\n\t"
//    "movem.l #7966,-(%sp)\n\t"
//    "move.l 44(%sp),%d5\n\t"
//    "move.l 52(%sp),%d6\n\t"
//    "move.l 60(%sp),%d1\n\t"
//    "move.l 64(%sp),%d0\n\t"
//    "move.l %d1,%d7\n\t"
//    "add.l %d5,%d7\n\t"
//    "tst.l %d1\n\t"
//    "jle ftraxL234\n\t"
//    "move.l %d5,%d1\n\t"
//    "move.l %d7,%d5\n\t"
//    "move.l %d1,%d7\n\t"
//    "ftraxL234:\n\t"
//    "move.l %d0,%a3\n\t"
//    "add.l %d6,%a3\n\t"
//    "tst.l %d0\n\t"
//    "jle ftraxL235\n\t"
//    "move.l %d6,%d0\n\t"
//    "move.l %a3,%d6\n\t"
//    "move.l %d0,%a3\n\t"
//    "ftraxL235:\n\t"
//    "move.l 48(%sp),%d3\n\t"
//    "lea get_coordinatex_a,%a5\n\t"
//    "lea pset_only_a,%a6\n\t"
//    "ftraxL236:\n\t"
//    "cmp.l 56(%sp),%d3\n\t"
//    "jle ftraxL239\n\t"
//    "movem.l (%sp)+,#30968\n\t"
//    "rts\n\t"
//    "ftraxL239:\n\t"
//    "move.l %d3,-(%sp)\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l %a3,-(%sp)\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l %d7,-(%sp)\n\t"
//    "jsr (%a5)\n\t"
//    "lea (20,%sp),%sp\n\t"
//    "move.l %d0,%d4\n\t"
//    "move.l %d3,-(%sp)\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l %d6,-(%sp)\n\t"
//    "move.l 60(%sp),-(%sp)\n\t"
//    "move.l %d5,-(%sp)\n\t"
//    "jsr (%a5)\n\t"
//    "lea (20,%sp),%sp\n\t"
//    "move.l %d0,%a4\n\t"
//    "ftraxL237:\n\t"
//    "cmp.l %d4,%a4\n\t"
//    "jge ftraxL238\n\t"
//    "addq.l #1,%d3\n\t"
//    "jra ftraxL236\n\t"
//    "ftraxL238:\n\t"
//    "move.l 68(%sp),-(%sp)\n\t"
//    "move.l %d3,-(%sp)\n\t"
//    "move.l %d4,-(%sp)\n\t"
//    "jsr (%a6)\n\t"
//    "addq.l #1,%d4\n\t"
//    "lea (12,%sp),%sp\n\t"
//    "jra ftraxL237\n\t"
//);
asm(
    "filltrapezoidx_a:\n\t"
    "movem.l #7966,-(%sp)\n\t"
    "move.l 44(%sp),%d4\n\t"
    "move.l 48(%sp),%a3\n\t"
    "move.l 52(%sp),%d5\n\t"
    "move.l 60(%sp),%d1\n\t"
    "move.l 64(%sp),%d0\n\t"
    "move.l %d1,%a6\n\t"
    "add.l %d4,%a6\n\t"
    "tst.l %d1\n\t"
    "jle ftraxL285\n\t"
    "move.l %d4,%d1\n\t"
    "move.l %a6,%d4\n\t"
    "move.l %d1,%a6\n\t"
    "ftraxL285:\n\t"
    "move.l %d0,%d7\n\t"
    "add.l %d5,%d7\n\t"
    "tst.l %d0\n\t"
    "jle ftraxL286\n\t"
    "move.l %d5,%d0\n\t"
    "move.l %d7,%d5\n\t"
    "move.l %d0,%d7\n\t"
    "ftraxL286:\n\t"
    "move.l %a3,%d3\n\t"
    "lea get_coordinatex_a,%a4\n\t"
    "lea drawhlinex_a,%a5\n\t"
    "ftraxL287:\n\t"
    "cmp.l 56(%sp),%d3\n\t"
    "jle ftraxL288\n\t"
    "movem.l (%sp)+,#30968\n\t"
    "rts\n\t"
    "ftraxL288:\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l 60(%sp),-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l %a6,-(%sp)\n\t"
    "jsr (%a4)\n\t"
    "lea (20,%sp),%sp\n\t"
    "move.l %d0,%d6\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l 60(%sp),-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "jsr (%a4)\n\t"
    "lea (20,%sp),%sp\n\t"
    "move.l 68(%sp),-(%sp)\n\t"
    "sub.l %d6,%d0\n\t"
    "move.l %d0,-(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "move.l 56(%sp),-(%sp)\n\t"
    "jsr (%a5)\n\t"
    "addq.l #1,%d3\n\t"
    "lea (20,%sp),%sp\n\t"
    "jra ftraxL287\n\t"
);
asm(
    "filltrianglex_a:\n\t"
    "movem.l #7966,-(%sp)\n\t"
    "move.l 40(%sp),%a5\n\t"
    "move.l 44(%sp),%a3\n\t"
    "move.l 48(%sp),%d5\n\t"
    "move.l 52(%sp),%d7\n\t"
    "move.l 56(%sp),%d4\n\t"
    "move.l 60(%sp),%d6\n\t"
    "move.l 64(%sp),%d3\n\t"
    "move.l 68(%sp),%a6\n\t"
    "cmp.l %d5,%d4\n\t"
    "jlt ftrixL242\n\t"
    "cmp.l %d5,%d3\n\t"
    "jge ftrixL243\n\t"
    "move.l %d5,%d0\n\t"
    "move.l %d3,%d5\n\t"
    "move.l %d0,%d3\n\t"
    "move.l %a3,%d0\n\t"
    "move.l %d6,%a3\n\t"
    "move.l %d0,%d6\n\t"
    "ftrixL243:\n\t"
    "cmp.l %d3,%d4\n\t"
    "jgt ftrixL244\n\t"
    "move.l %d3,%d0\n\t"
    "move.l %d4,%d3\n\t"
    "move.l %d0,%d4\n\t"
    "move.l %d6,%d0\n\t"
    "move.l %d7,%d6\n\t"
    "move.l %d0,%d7\n\t"
    "ftrixL244:\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d4,-(%sp)\n\t"
    "move.l %d7,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "jsr get_coordinatex_a\n\t"
    "lea (20,%sp),%sp\n\t"
    "move.l %d0,%a4\n\t"
    "sub.l %d6,%a4\n\t"
    "move.l %a6,-(%sp)\n\t"
    "move.l %a4,-(%sp)\n\t"
    "clr.l -(%sp)\n\t"
    "move.l %d3,-(%sp)\n\t"
    "move.l %d6,-(%sp)\n\t"
    "move.l %d5,-(%sp)\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l %a5,-(%sp)\n\t"
    "jsr filltrapezoidx_a\n\t"
    "lea (32,%sp),%sp\n\t"
    "move.l %a6,68(%sp)\n\t"
    "clr.l 64(%sp)\n\t"
    "move.l %a4,60(%sp)\n\t"
    "move.l %d4,56(%sp)\n\t"
    "move.l %d7,52(%sp)\n\t"
    "move.l %d3,48(%sp)\n\t"
    "move.l %d6,44(%sp)\n\t"
    "move.l %a5,40(%sp)\n\t"
    "movem.l (%sp)+,#30968\n\t"
    "jra filltrapezoidx_a\n\t"
    "ftrixL246:\n\t"
    "move.l %d3,%d0\n\t"
    "move.l %d4,%d3\n\t"
    "move.l %d5,%d4\n\t"
    "move.l %d0,%d5\n\t"
    "move.l %d6,%d0\n\t"
    "move.l %d7,%d6\n\t"
    "move.l %a3,%d7\n\t"
    "move.l %d0,%a3\n\t"
    "jra ftrixL244\n\t"
    "ftrixL242:\n\t"
    "cmp.l %d4,%d3\n\t"
    "jlt ftrixL246\n\t"
    "move.l %d5,%d0\n\t"
    "move.l %d4,%d5\n\t"
    "move.l %d0,%d4\n\t"
    "move.l %a3,%d0\n\t"
    "move.l %d7,%a3\n\t"
    "move.l %d0,%d7\n\t"
    "jra ftrixL243\n\t"
);
asm(
    "tab_sin_a:\n\t"
    "move.l 4(%sp),%d0\n\t"
    "cmp.l #360,%d0\n\t"
    "jhi tsinL411\n\t"
    "pea 5.w\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr __divsi3\n\t"
    "addq.l #8,%sp\n\t"
    "lsl.l #2,%d0\n\t"
    "lea sine_table_a,%a0\n\t"
    "move.l (%a0,%d0.l),%d0\n\t"
    "tsinL409:\n\t"
    "rts\n\t"
    "tsinL411:\n\t"
    "moveq #0,%d0\n\t"
    "jra tsinL409\n\t"
    "tab_cos_a:\n\t"
    "move.l 4(%sp),%a0\n\t"
    "cmp.w #360,%a0\n\t"
    "jhi tcosL414\n\t"
    "pea 5.w\n\t"
    "pea 90(%a0)\n\t"
    "jsr __divsi3\n\t"
    "addq.l #8,%sp\n\t"
    "lsl.l #2,%d0\n\t"
    "lea sine_table_a,%a0\n\t"
    "move.l (%a0,%d0.l),%d0\n\t"
    "tcosL412:\n\t"
    "rts\n\t"
    "tcosL414:\n\t"
    "moveq #0,%d0\n\t"
    "jra tcosL412\n\t"
);
asm(
    "sine_table_a:\n\t"
    ".long	0\n\t"
    ".long	1035108016\n\t"
    ".long	1043452117\n\t"
    ".long	1048871917\n\t"
    ".long	1051663682\n\t"
    ".long	1054368109\n\t"
    ".long	1056964608\n\t"
    ".long	1058199015\n\t"
    ".long	1059360186\n\t"
    ".long	1060439284\n\t"
    ".long	1061428092\n\t"
    ".long	1062319090\n\t"
    ".long	1063105495\n\t"
    ".long	1063781322\n\t"
    ".long	1064341426\n\t"
    ".long	1064781546\n\t"
    ".long	1065098333\n\t"
    ".long	1065289374\n\t"
    ".long	1065353216\n\t"
    ".long	1065289374\n\t"
    ".long	1065098333\n\t"
    ".long	1064781546\n\t"
    ".long	1064341426\n\t"
    ".long	1063781322\n\t"
    ".long	1063105495\n\t"
    ".long	1062319090\n\t"
    ".long	1061428092\n\t"
    ".long	1060439284\n\t"
    ".long	1059360186\n\t"
    ".long	1058199015\n\t"
    ".long	1056964608\n\t"
    ".long	1054368109\n\t"
    ".long	1051663682\n\t"
    ".long	1048871917\n\t"
    ".long	1043452117\n\t"
    ".long	1035108016\n\t"
    ".long	0\n\t"
    ".long	-1112375632\n\t"
    ".long	-1104031531\n\t"
    ".long	-1098611731\n\t"
    ".long	-1095819966\n\t"
    ".long	-1093115539\n\t"
    ".long	-1090519040\n\t"
    ".long	-1089284633\n\t"
    ".long	-1088123462\n\t"
    ".long	-1087044364\n\t"
    ".long	-1086055556\n\t"
    ".long	-1085164558\n\t"
    ".long	-1084378153\n\t"
    ".long	-1083702326\n\t"
    ".long	-1083142222\n\t"
    ".long	-1082702102\n\t"
    ".long	-1082385315\n\t"
    ".long	-1082194274\n\t"
    ".long	-1082130432\n\t"
    ".long	-1082194274\n\t"
    ".long	-1082385315\n\t"
    ".long	-1082702102\n\t"
    ".long	-1083142222\n\t"
    ".long	-1083702326\n\t"
    ".long	-1084378153\n\t"
    ".long	-1085164558\n\t"
    ".long	-1086055556\n\t"
    ".long	-1087044364\n\t"
    ".long	-1088123462\n\t"
    ".long	-1089284633\n\t"
    ".long	-1090519040\n\t"
    ".long	-1093115539\n\t"
    ".long	-1095819966\n\t"
    ".long	-1098611728\n\t"
    ".long	-1104031531\n\t"
    ".long	-1112375632\n\t"
    ".long	-2147483648\n\t"
    ".long	1035108016\n\t"
    ".long	1043452117\n\t"
    ".long	1048871917\n\t"
    ".long	1051663682\n\t"
    ".long	1054368109\n\t"
    ".long	1056964608\n\t"
    ".long	1058199015\n\t"
    ".long	1059360186\n\t"
    ".long	1060439284\n\t"
    ".long	1061428092\n\t"
    ".long	1062319090\n\t"
    ".long	1063105495\n\t"
    ".long	1063781322\n\t"
    ".long	1064341426\n\t"
    ".long	1064781546\n\t"
    ".long	1065098333\n\t"
    ".long	1065289374\n\t"
    ".long	1065353216\n\t"
);
//asm(
//    "tab_opposite_edgex_a:\n\t"
//    "move.l %a3,-(%sp)\n\t"
//    "move.l 8(%sp),%d0\n\t"
//    "jpl toexL429\n\t"
//    "neg.l %d0\n\t"
//    "toexL429:\n\t"
//    "move.l %d0,%d1\n\t"
//    "lsl.l #5,%d1\n\t"
//    "sub.l %d0,%d1\n\t"
//    "add.l %d1,%d1\n\t"
//    "add.l %d1,%d1\n\t"
//    "add.l %d1,%d0\n\t"
//    "move.l %d0,%d1\n\t"
//    "add.l %d0,%d1\n\t"
//    "add.l %d1,%d1\n\t"
//    "add.l %d1,%d0\n\t"
//    "lsl.l #4,%d0\n\t"
//    "lea __divsi3,%a3\n\t"
//    "move.l 12(%sp),-(%sp)\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "addq.l #8,%sp\n\t"
//    "cmp.l #10000,%d0\n\t"
//    "jgt toexL431\n\t"
//    "pea 100.w\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "addq.l #8,%sp\n\t"
//    "lsl.l #2,%d0\n\t"
//    "lea opposite_edge_table_a,%a0\n\t"
//    "move.l (%a0,%d0.l),-(%sp)\n\t"
//    "move.l 20(%sp),-(%sp)\n\t"
//    "jsr __mulsi3\n\t"
//    "addq.l #8,%sp\n\t"
//    "pea 10000.w\n\t"
//    "move.l %d0,-(%sp)\n\t"
//    "jsr (%a3)\n\t"
//    "addq.l #8,%sp\n\t"
//    "toexL428:\n\t"
//    "move.l (%sp)+,%a3\n\t"
//    "rts\n\t"
//    "toexL431:\n\t"
//    "moveq #0,%d0\n\t"
//    "jra toexL428\n\t"
//);
asm(
    "tab_opposite_edgex_a:\n\t"
    "move.l %a3,-(%sp)\n\t"
    "move.l 8(%sp),%d0\n\t"
    "jpl datxL429\n\t"
    "neg.l %d0\n\t"
    "datxL429:\n\t"
    "move.l %d0,%d1\n\t"
    "lsl.l #5,%d1\n\t"
    "sub.l %d0,%d1\n\t"
    "add.l %d1,%d1\n\t"
    "add.l %d1,%d1\n\t"
    "add.l %d1,%d0\n\t"
    "move.l %d0,%d1\n\t"
    "add.l %d0,%d1\n\t"
    "add.l %d1,%d1\n\t"
    "add.l %d1,%d0\n\t"
    "lsl.l #4,%d0\n\t"
    "lea __divsi3,%a3\n\t"
    "move.l 12(%sp),-(%sp)\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "addq.l #8,%sp\n\t"
    "cmp.l #10000,%d0\n\t"
    "jgt datxL431\n\t"
    "pea 100.w\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "addq.l #8,%sp\n\t"
    "lsl.l #2,%d0\n\t"
    "lea orthogonal_dim_table_asm,%a0\n\t"
    "move.l (%a0,%d0.l),-(%sp)\n\t"
    "move.l 20(%sp),-(%sp)\n\t"
    "jsr __mulsi3\n\t"
    "addq.l #8,%sp\n\t"
    "pea 10000.w\n\t"
    "move.l %d0,-(%sp)\n\t"
    "jsr (%a3)\n\t"
    "addq.l #8,%sp\n\t"
    "datxL428:\n\t"
    "move.l (%sp)+,%a3\n\t"
    "rts\n\t"
    "datxL431:\n\t"
    "moveq #0,%d0\n\t"
    "jra datxL428\n\t"
);
asm(
    "orthogonal_dim_table_asm:\n\t"
    ".long	10000\n\t"
    ".long	9999\n\t"
    ".long	9997\n\t"
    ".long	9995\n\t"
    ".long	9991\n\t"
    ".long	9987\n\t"
    ".long	9981\n\t"
    ".long	9975\n\t"
    ".long	9967\n\t"
    ".long	9959\n\t"
    ".long	9949\n\t"
    ".long	9939\n\t"
    ".long	9927\n\t"
    ".long	9915\n\t"
    ".long	9901\n\t"
    ".long	9886\n\t"
    ".long	9871\n\t"
    ".long	9854\n\t"
    ".long	9836\n\t"
    ".long	9817\n\t"
    ".long	9797\n\t"
    ".long	9777\n\t"
    ".long	9754\n\t"
    ".long	9731\n\t"
    ".long	9707\n\t"
    ".long	9682\n\t"
    ".long	9656\n\t"
    ".long	9628\n\t"
    ".long	9600\n\t"
    ".long	9570\n\t"
    ".long	9539\n\t"
    ".long	9507\n\t"
    ".long	9474\n\t"
    ".long	9439\n\t"
    ".long	9404\n\t"
    ".long	9367\n\t"
    ".long	9329\n\t"
    ".long	9290\n\t"
    ".long	9249\n\t"
    ".long	9208\n\t"
    ".long	9165\n\t"
    ".long	9120\n\t"
    ".long	9075\n\t"
    ".long	9028\n\t"
    ".long	8979\n\t"
    ".long	8930\n\t"
    ".long	8879\n\t"
    ".long	8826\n\t"
    ".long	8772\n\t"
    ".long	8717\n\t"
    ".long	8660\n\t"
    ".long	8601\n\t"
    ".long	8541\n\t"
    ".long	8479\n\t"
    ".long	8416\n\t"
    ".long	8351\n\t"
    ".long	8284\n\t"
    ".long	8216\n\t"
    ".long	8146\n\t"
    ".long	8074\n\t"
    ".long	8000\n\t"
    ".long	7924\n\t"
    ".long	7846\n\t"
    ".long	7765\n\t"
    ".long	7683\n\t"
    ".long	7599\n\t"
    ".long	7512\n\t"
    ".long	7423\n\t"
    ".long	7332\n\t"
    ".long	7238\n\t"
    ".long	7141\n\t"
    ".long	7042\n\t"
    ".long	6939\n\t"
    ".long	6834\n\t"
    ".long	6726\n\t"
    ".long	6614\n\t"
    ".long	6499\n\t"
    ".long	6380\n\t"
    ".long	6257\n\t"
    ".long	6131\n\t"
    ".long	6000\n\t"
    ".long	5864\n\t"
    ".long	5723\n\t"
    ".long	5577\n\t"
    ".long	5425\n\t"
    ".long	5267\n\t"
    ".long	5102\n\t"
    ".long	4930\n\t"
    ".long	4749\n\t"
    ".long	4559\n\t"
    ".long	4358\n\t"
    ".long	4146\n\t"
    ".long	3919\n\t"
    ".long	3675\n\t"
    ".long	3411\n\t"
    ".long	3122\n\t"
    ".long	2800\n\t"
    ".long	2431\n\t"
    ".long	1989\n\t"
    ".long	1410\n\t"
    ".long	0\n\t"
);

asm(
    "tab_orthogonal_dim_asm:\n"
    "\tmove.l %a3,-(%sp)\n"
    "\tmove.l 8(%sp),%d0\n"
    "\tjpl filasm325\n"
    "\tneg.l %d0\n"
    "filasm325:\n"
    "\tmove.l %d0,%d1\n"
    "\tlsl.l #5,%d1\n"
    "\tsub.l %d0,%d1\n"
    "\tadd.l %d1,%d1\n"
    "\tadd.l %d1,%d1\n"
    "\tadd.l %d1,%d0\n"
    "\tmove.l %d0,%d1\n"
    "\tadd.l %d0,%d1\n"
    "\tadd.l %d1,%d1\n"
    "\tadd.l %d1,%d0\n"
    "\tlsl.l #4,%d0\n"
    "\tlea __divsi3,%a3\n"
    "\tmove.l 12(%sp),-(%sp)\n"
    "\tmove.l %d0,-(%sp)\n"
    "\tjsr (%a3)\n"
    "\taddq.l #8,%sp\n"
    "\tcmp.l #10000,%d0\n"
    "\tjgt filasm327\n"
    "\tpea 100.w\n"
    "\tmove.l %d0,-(%sp)\n"
    "\tjsr (%a3)\n"
    "\taddq.l #8,%sp\n"
    "\tlsl.l #2,%d0\n"
    "\tlea orthogonal_dim_table_asm,%a0\n"
    "\tmove.l (%a0,%d0.l),-(%sp)\n"
    "\tmove.l 20(%sp),-(%sp)\n"
    "\tjsr __mulsi3\n"
    "\taddq.l #8,%sp\n"
    "\tpea 10000.w\n"
    "\tmove.l %d0,-(%sp)\n"
    "\tjsr (%a3)\n"
    "\taddq.l #8,%sp\n"
    "filasm324:\n"
    "\tmove.l (%sp)+,%a3\n"
    "\trts\n"
    "filasm327:\n"
    "\tmoveq #0,%d0\n"
    "\tjra filasm324\n"
);

asm(
    "\tg_gmemory_asm=0xc00000\n"
    "fillellipse_asm:\n"
    "\tmovem.l #7960,-(%sp)\n"
    "\tmove.l 40(%sp),%d3\n"
    "\tmove.l 48(%sp),%d0\n"
    "\tmove.l 44(%sp),%d7\n"
    "\tjpl filasm333\n"
    "\taddq.l #1,%d7\n"
    "filasm333:\n"
    "\tasr.l #1,%d7\n"
    "\tmove.l %d7,%d4\n"
    "\tadd.l 36(%sp),%d4\n"
    "\tmove.l %d0,%d1\n"
    "\tjpl filasm334\n"
    "\taddq.l #1,%d1\n"
    "filasm334:\n"
    "\tasr.l #1,%d1\n"
    "\tmove.l %d1,%a4\n"
    "\tmove.l %d1,%d6\n"
    "\tadd.l %d3,%d6\n"
    "\tmove.l %d0,%d5\n"
    "\tadd.l %d3,%d5\n"
    "\tlea _Z18tab_orthogonal_dimiii,%a3\n"
    "filasm329:\n"
    "\tcmp.l %d5,%d3\n"
    "\tjlt filasm332\n"
    "\tmovem.l (%sp)+,#6392\n"
    "\trts\n"
    "filasm332:\n"
    "\tmove.l %d7,-(%sp)\n"
    "\tmove.l %a4,-(%sp)\n"
    "\tmove.l %d3,%d0\n"
    "\tsub.l %d6,%d0\n"
    "\tmove.l %d0,-(%sp)\n"
    "\tjsr (%a3)\n"
    "\tlea (12,%sp),%sp\n"
    "\tmove.l %d3,%d1\n"
    "\tmoveq #10,%d2\n"
    "\tlsl.l %d2,%d1\n"
    "\tmove.l %d1,%a0\n"
    "\tadd.l #g_gmemory_asm,%a0\n"
    "\tmove.l %d4,%d1\n"
    "\tsub.l %d0,%d1\n"
    "\tadd.l %d4,%d0\n"
    "filasm330:\n"
    "\tcmp.l %d1,%d0\n"
    "\tjge filasm331\n"
    "\taddq.l #1,%d3\n"
    "\tjra filasm329\n"
    "filasm331:\n"
    "\tmove.l %d1,%a1\n"
    "\tadd.l %d1,%a1\n"
    "\tmove.w 54(%sp),(%a0,%a1.l)\n"
    "\taddq.l #1,%d1\n"
    "\tjra filasm330\n"
);

asm(
    "fillroundedrectangle_asm:\n"
    "\tsubq.l #8,%sp\n"
    "\tmovem.l #7966,-(%sp)\n"
    "\tmove.l 52(%sp),%a3\n"
    "\tmove.l 56(%sp),%d3\n"
    "\tmove.l 68(%sp),%d7\n"
    "\tmove.l 72(%sp),%d6\n"
    "\tmove.l 76(%sp),%d5\n"
    "\tlea (%a3,%d7.l),%a0\n"
    "\tmove.l %a0,40(%sp)\n"
    "\tmove.l %d3,%d4\n"
    "\tadd.l %d6,%d4\n"
    "\tmove.l %d3,%a5\n"
    "\tadd.l 64(%sp),%a5\n"
    "\tmove.l %a5,%d0\n"
    "\tmoveq #10,%d1\n"
    "\tlsl.l %d1,%d0\n"
    "\tmove.l %d0,%a6\n"
    "\tadd.l #g_gmemory_asm-1024,%a6\n"
    "\tlea _Z18tab_orthogonal_dimiii,%a4\n"
    "filasm336:\n"
    "\tcmp.l %d3,%d4\n"
    "\tjgt filasm341\n"
    "\tsub.l %d6,%a5\n"
    "\tmove.l 60(%sp),%d1\n"
    "\tadd.l %a3,%d1\n"
    "filasm342:\n"
    "\tcmp.l %a5,%d4\n"
    "\tjge filasm335\n"
    "\tmove.l %d4,%d0\n"
    "\tmoveq #10,%d2\n"
    "\tlsl.l %d2,%d0\n"
    "\tmove.l %d0,%a0\n"
    "\tadd.l #g_gmemory_asm,%a0\n"
    "\tmove.l %a3,%d0\n"
    "\tjra filasm345\n"
    "filasm341:\n"
    "\tmove.l %d7,-(%sp)\n"
    "\tmove.l %d6,-(%sp)\n"
    "\tmove.l %d3,%d2\n"
    "\tsub.l %d4,%d2\n"
    "\tmove.l %d2,-(%sp)\n"
    "\tjsr (%a4)\n"
    "\tlea (12,%sp),%sp\n"
    "\tmove.l %d0,%d1\n"
    "\tadd.l %d0,%d1\n"
    "\tadd.l %a3,%d1\n"
    "\tadd.l 60(%sp),%d1\n"
    "\tsub.l %d7,%d1\n"
    "\tmove.l %d1,36(%sp)\n"
    "\tmove.l 40(%sp),%a0\n"
    "\tsub.l %d0,%a0\n"
    "\tmove.l %d3,%d2\n"
    "\tmoveq #10,%d1\n"
    "\tlsl.l %d1,%d2\n"
    "\tmove.l %d2,%a2\n"
    "\tadd.l #g_gmemory_asm,%a2\n"
    "\tmove.l %a0,%a1\n"
    "\tmove.l 36(%sp),%d1\n"
    "\tsub.l %d0,%d1\n"
    "filasm337:\n"
    "\tcmp.l %a1,%d1\n"
    "\tjge filasm338\n"
    "filasm339:\n"
    "\tcmp.l %a0,%d1\n"
    "\tjge filasm340\n"
    "\taddq.l #1,%d3\n"
    "\tlea (-1024,%a6),%a6\n"
    "\tjra filasm336\n"
    "filasm338:\n"
    "\tmove.l %a1,%d0\n"
    "\tadd.l %a1,%d0\n"
    "\tmove.w %d5,(%a2,%d0.l)\n"
    "\taddq.l #1,%a1\n"
    "\tjra filasm337\n"
    "filasm340:\n"
    "\tlea (%a0,%a0.l),%a1\n"
    "\tmove.w %d5,(%a6,%a1.l)\n"
    "\taddq.l #1,%a0\n"
    "\tjra filasm339\n"
    "filasm343:\n"
    "\tmove.l %d0,%a1\n"
    "\tadd.l %d0,%a1\n"
    "\tmove.w %d5,(%a0,%a1.l)\n"
    "\taddq.l #1,%d0\n"
    "filasm345:\n"
    "\tcmp.l %d0,%d1\n"
    "\tjge filasm343\n"
    "\taddq.l #1,%d4\n"
    "\tjra filasm342\n"
    "filasm335:\n"
    "\tmovem.l (%sp)+,#30968\n"
    "\taddq.l #8,%sp\n"
    "\trts\n"
);

asm(
    "filltrapezoid_asm:\n"
    "\tmovem.l #7966,-(%sp)\n"
    "\tmove.l 44(%sp),%d5\n"
    "\tmove.l 48(%sp),%a4\n"
    "\tmove.l 52(%sp),%d6\n"
    "\tmove.l 56(%sp),%d7\n"
    "\tmove.l 60(%sp),%d1\n"
    "\tmove.l 64(%sp),%d0\n"
    "\tmove.l %d1,%a3\n"
    "\tadd.l %d5,%a3\n"
    "\ttst.l %d1\n"
    "\tjle filasm299\n"
    "\tmove.l %d5,%d1\n"
    "\tmove.l %a3,%d5\n"
    "\tmove.l %d1,%a3\n"
    "filasm299:\n"
    "\tmove.l %d0,%a6\n"
    "\tadd.l %d6,%a6\n"
    "\ttst.l %d0\n"
    "\tjle filasm300\n"
    "\tmove.l %d6,%d0\n"
    "\tmove.l %a6,%d6\n"
    "\tmove.l %d0,%a6\n"
    "filasm300:\n"
    "\tmove.l %a4,%d4\n"
    "\tlea get_coordinatex_a,%a5\n"
    "filasm301:\n"
    "\tcmp.l %d4,%d7\n"
    "\tjge filasm304\n"
    "\tmovem.l (%sp)+,#30968\n"
    "\trts\n"
    "filasm304:\n"
    "\tmove.l %d4,-(%sp)\n"
    "\tmove.l %d7,-(%sp)\n"
    "\tmove.l %a6,-(%sp)\n"
    "\tmove.l %a4,-(%sp)\n"
    "\tmove.l %a3,-(%sp)\n"
    "\tjsr (%a5)\n"
    "\tlea (20,%sp),%sp\n"
    "\tmove.l %d0,%d3\n"
    "\tmove.l %d4,-(%sp)\n"
    "\tmove.l %d7,-(%sp)\n"
    "\tmove.l %d6,-(%sp)\n"
    "\tmove.l %a4,-(%sp)\n"
    "\tmove.l %d5,-(%sp)\n"
    "\tjsr (%a5)\n"
    "\tlea (20,%sp),%sp\n"
    "\tmove.l %d4,%d1\n"
    "\tmoveq #10,%d2\n"
    "\tlsl.l %d2,%d1\n"
    "\tadd.l #g_gmemory_asm,%d1\n"
    "filasm302:\n"
    "\tcmp.l %d0,%d3\n"
    "\tjle filasm303\n"
    "\taddq.l #1,%d4\n"
    "\tjra filasm301\n"
    "filasm303:\n"
    "\tmove.l %d3,%a0\n"
    "\tadd.l %d3,%a0\n"
    "\tmove.w 70(%sp),(%a0,%d1.l)\n"
    "\taddq.l #1,%d3\n"
    "\tjra filasm302\n"
);

asm(
    "filltriangle_asm:\n"
    "\tmovem.l #7966,-(%sp)\n"
    "\tmove.l 40(%sp),%a5\n"
    "\tmove.l 44(%sp),%a3\n"
    "\tmove.l 48(%sp),%d5\n"
    "\tmove.l 52(%sp),%d7\n"
    "\tmove.l 56(%sp),%d4\n"
    "\tmove.l 60(%sp),%d6\n"
    "\tmove.l 64(%sp),%d3\n"
    "\tmove.l 68(%sp),%a6\n"
    "\tcmp.l %d5,%d4\n"
    "\tjlt filasm306\n"
    "\tcmp.l %d5,%d3\n"
    "\tjge filasm307\n"
    "\tmove.l %d5,%d0\n"
    "\tmove.l %d3,%d5\n"
    "\tmove.l %d0,%d3\n"
    "\tmove.l %a3,%d0\n"
    "\tmove.l %d6,%a3\n"
    "\tmove.l %d0,%d6\n"
    "filasm307:\n"
    "\tcmp.l %d3,%d4\n"
    "\tjgt filasm308\n"
    "\tmove.l %d3,%d0\n"
    "\tmove.l %d4,%d3\n"
    "\tmove.l %d0,%d4\n"
    "\tmove.l %d6,%d0\n"
    "\tmove.l %d7,%d6\n"
    "\tmove.l %d0,%d7\n"
    "filasm308:\n"
    "\tmove.l %d3,-(%sp)\n"
    "\tmove.l %d4,-(%sp)\n"
    "\tmove.l %d7,-(%sp)\n"
    "\tmove.l %d5,-(%sp)\n"
    "\tmove.l %a3,-(%sp)\n"
    "\tjsr get_coordinatex_a\n"
    "\tlea (20,%sp),%sp\n"
    "\tmove.l %d0,%a4\n"
    "\tsub.l %d6,%a4\n"
    "\tmove.l %a6,-(%sp)\n"
    "\tmove.l %a4,-(%sp)\n"
    "\tclr.l -(%sp)\n"
    "\tmove.l %d3,-(%sp)\n"
    "\tmove.l %d6,-(%sp)\n"
    "\tmove.l %d5,-(%sp)\n"
    "\tmove.l %a3,-(%sp)\n"
    "\tmove.l %a5,-(%sp)\n"
    "\tjsr filltrapezoid_asm\n"
    "\tlea (32,%sp),%sp\n"
    "\tmove.l %a6,68(%sp)\n"
    "\tclr.l 64(%sp)\n"
    "\tmove.l %a4,60(%sp)\n"
    "\tmove.l %d4,56(%sp)\n"
    "\tmove.l %d7,52(%sp)\n"
    "\tmove.l %d3,48(%sp)\n"
    "\tmove.l %d6,44(%sp)\n"
    "\tmove.l %a5,40(%sp)\n"
    "\tmovem.l (%sp)+,#30968\n"
    "\tjra filltrapezoid_asm\n"
    "filasm310:\n"
    "\tmove.l %d3,%d0\n"
    "\tmove.l %d4,%d3\n"
    "\tmove.l %d5,%d4\n"
    "\tmove.l %d0,%d5\n"
    "\tmove.l %d6,%d0\n"
    "\tmove.l %d7,%d6\n"
    "\tmove.l %a3,%d7\n"
    "\tmove.l %d0,%a3\n"
    "\tjra filasm308\n"
    "filasm306:\n"
    "\tcmp.l %d4,%d3\n"
    "\tjlt filasm310\n"
    "\tmove.l %d5,%d0\n"
    "\tmove.l %d4,%d5\n"
    "\tmove.l %d0,%d4\n"
    "\tmove.l %a3,%d0\n"
    "\tmove.l %d7,%a3\n"
    "\tmove.l %d0,%d7\n"
    "\tjra filasm307\n"
);



